#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push checks...🍺"

echo "Building the project🏗️"

npm run build || (
  echo "Build failed. ❌ "
  exit 1
)

echo "Build completed successfully. ✅ "